services:
  sveltekit-app:
    container_name: "branddomains"
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ORIGIN=https://branddomains.psionicalch.com
    ports:
      - "3001:3000"
